### ISSUE TITLE
demo 的apk闪退

### ISSUE THREAD

**Issue by every-easy** [buhuiming/flutter_nb#2]
用demo的apk，华为手机安装，闪退掉；
自己编译也是闪退掉了

**Comment by buhuiming** [comment]
编译运行后闪退，输入什么日志

**Comment by lupming** [comment]
我这demo也是闪退..xiaomiM9.
错误如下:
2019-07-03 10:51:03.747 1614-5747/? E/ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
2019-07-03 10:51:03.747 731-731/? E/ANDR-IOP: IOP HAL: Received pkg_name = com.bhm.flutter.flutternb pid = -1
2019-07-03 10:51:03.753 731-772/? E/ANDR-IOP: io prefetch is disabled
2019-07-03 10:51:03.865 10133-10133/com.bhm.flutter.flutternb E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bhm.flutter.flutternb, PID: 10133
    java.lang.ClassCastException: com.bhm.flutter.flutternb.FlutterNBApplication cannot be cast to android.app.AppComponentFactory
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:229)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:733)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:812)
        at android.app.LoadedApk.getResources(LoadedApk.java:1034)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2357)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5821)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6815)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: don't request, because recommend screen can't show
2019-07-03 10:51:03.915 2279-2279/? E/Launcher.RecommendLog: folder display and try to request recommend list
2019-07-03 10:51:03.922 4496-4596/? E/PowerKeeper.Sensor: setAppSensorsControlPolicyjava.lang.UnsupportedOperationException
2019-07-03 10:51:03.924 4496-4596/? E/PowerKeeper.Sensor: setAppSensorsControlPolicyjava.lang.UnsupportedOperationException
2019-07-03 10:51:04.821 1614-1674/? E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
2019-07-03 10:51:05.079 637-674/? E/DnsProxyListener: block dns query from uid = 10024
2019-07-03 10:51:05.079 637-674/? E/DnsProxyListener: block dns query from uid = 10024

**Comment by lupming** [comment]
E:\CodeManage\Android\flutter_nb-master>flutter --version
Flutter 1.6.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bc7bc94083 (6 weeks ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

另外不知道demo对androidX的兼容如何?还请作者抽空看看，谢谢。

**Comment by lupming** [comment]
着急等待ing...

**Comment by sunshinewei** [comment]
> 用demo的apk，华为手机安装，闪退掉；
> 自己编译也是闪退掉了

result.success(o)只运行在UI线程中，修改运行到UI线程就可以了

**Comment by lupming** [comment]
result.success(o)只运行在UI线程中，修改运行到UI线程就可以了.
是进程?具体可以多讲解下吗??

**Comment by lupming** [comment]
> > 用demo的apk，华为手机安装，闪退掉；
> > 自己编译也是闪退掉了
> 
> result.success(o)只运行在UI线程中，修改运行到UI线程就可以了

esult.success(o)只运行在UI线程中，修改运行到UI线程就可以了.
是进程?具体可以多讲解下吗??

**Comment by lupming** [comment]
> > 用demo的apk，华为手机安装，闪退掉；
> > 自己编译也是闪退掉了
> 
> result.success(o)只运行在UI线程中，修改运行到UI线程就可以了
是进程?具体可以多讲解下吗??

**Comment by buhuiming** [comment]
这个日志闪退已经处理了，升级一下fluttersdk版本
